DROP TABLE IF EXISTS raw_tmt_stage;

CREATE TABLE raw_tmt_stage (
    site_id text,
    protein_id text,
    gene_symbol text,
    prot_description text,
    site_position text,
    motif text,
    max_score text,
    low_bound text,
    high_bound text,
    best_search_id text,
    best_peptide_id text,
    best_scan text,
    best_search_name text,
    file_name text,
    redundancy text,
    sequence text,
    num_matching_comp_sites text,
    num_quant_comp_sites text,
    default_spectral_counts text,
    default_num_quant text,
    tmt_126 text,
    tmt_127n text,
    tmt_127c text,
    tmt_128n text,
    tmt_128c text,
    tmt_129n text,
    tmt_129c text,
    tmt_130n text,
    tmt_130c text,
    tmt_131n text,
    tmt_131c text,
    tmt_132n text,
    tmt_132c text,
    tmt_133n text,
    tmt_133c text,
    tmt_134n text,
    tmt_134c text,
    tmt_135 text,
    quantified_peptides text
);

